# Generated by Django 3.0.8 on 2020-07-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_activeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeuser',
            name='active_connections',
            field=models.IntegerField(default=0),
        ),
    ]
